name: cosmo-lidar-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - astropy
  - scipy
  - jupyter
  - pip
  - pip:
      - pycraf
      - pytest
      - notebook